Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;

namespace LibreriaOasis.Controllers
{
    public class InicioController : Controller
    {

        //ldc_18
        // GET: Inicio
        public ActionResult Index()
        {
            libreria_oasisEntities context = new libreria_oasisEntities();

            if (null != Session["id"])
            {
                int id = (int)Session["id"];
                user_admin admin = context.user_admin.Where(u=>u.id_admin == id).FirstOrDefault();
                ViewBag.admin = admin;
            }
            product pro = new product();
            List<product> products = context.product.ToList();
            ViewBag.products = products;
            
            return View();
        }

        [HttpPost]
        public ActionResult createProduct(string name, string description_product, double precio, int stock)
        {
            libreria_oasisEntities context = new libreria_oasisEntities();
            product pro = new product();
            pro.name = name;
            pro.stock = stock;
            pro.description_product = description_product;
            pro.precio = precio;
            context.product.Add(pro);
            context.SaveChanges();
            return Redirect("~/Inicio/index");
        }

        [HttpGet]
        public ActionResult deleteProduct(int id)
        {
            libreria_oasisEntities context = new libreria_oasisEntities();
            product product = context.product.Find(id);
            context.product.Remove(product);
            context.SaveChanges();
            return Redirect("~/Inicio/index");
        }

        [HttpGet]
        public ActionResult editProduct(int id)
        {
            libreria_oasisEntities context = new libreria_oasisEntities();
            product product = context.product.Find(id);
            ViewBag.product = product;
            return View();
        }

        [HttpPost]
        public ActionResult editTheProduct(string name, string description_product, double precio, int stock, int id)
        {
            libreria_oasisEntities context = new libreria_oasisEntities();
            product pro = context.product.Find(id);
            pro.name = name;
            pro.stock = stock;
            pro.description_product = description_product;
            pro.precio = precio;
            context.product.Attach(pro);
            context.Entry(pro).State = EntityState.Modified;
            context.SaveChanges();
            return Redirect("~/Inicio/index");
        }

        [HttpPost]
        public ActionResult createAdmin(string name,string mail,string pass)
        {
            libreria_oasisEntities context = new libreria_oasisEntities();
            user_admin admin = new user_admin();
  
            if (pass != "ldc_18") {
                return Redirect("~/Inicio/index");
            }
            admin.pass = pass;
            admin.name = name;
            admin.mail = mail;
            context.user_admin.Add(admin);
            context.SaveChanges();
            return Redirect("~/Inicio/index");
        }

        [HttpPost]
        public ActionResult loginAdmin(string mail, string pass)
        {
            libreria_oasisEntities context = new libreria_oasisEntities();
            user_admin admin = context.user_admin
                               .Where(u => u.mail == mail)
                               .Where(u => u.pass == pass)
                               .FirstOrDefault();

            if (admin == null)
            {
                return Redirect("~/Inicio/index");
            }
            Session["id"] = admin.id_admin;
            context.user_admin.Add(admin);
            context.SaveChanges();
            return Redirect("~/Inicio/index");
        }

        public ActionResult logoutAdmin()
        {
            Session.Clear();
            return Redirect("~/Inicio/index");
        }
    }
}

Views/Inicio/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/myLayout.cshtml";
}

<h2>Index</h2>
@if (ViewBag.admin != null) {
    @ViewBag.admin.name<br />
    @ViewBag.admin.mail
}
<h3>create admin</h3>
@using (Html.BeginForm("createAdmin", "Inicio", FormMethod.Post))
{
    <input class="name" id="name" name="name" type="text" />
    <input class="mail" id="email" name="mail" type="email" />
    <input class="pass" id="pass" name="pass" type="password" />
    <input type="submit" />
}

<h3>login</h3>
@using (Html.BeginForm("loginAdmin", "Inicio", FormMethod.Post))
{
    <input class="mail" id="mail" name="mail" type="email" />
    <input class="pass" id="pass" name="pass" type="password"/>
    <input type="submit" />
}

<h3>create product</h3>
@using (Html.BeginForm("createProduct", "Inicio", FormMethod.Post))
{
    <input class="name" id="name" name="name" type="text"/>
    <input class="description_product" id="description_product" name="description_product" type="text"/>
    <input class="precio" id="precio" name="precio" type="number"/>
    <input class="stock" id="stock" name="stock" type="number"/>
    <input type="submit"/>
}

@{
    foreach (product p in ViewBag.products)
    {
        <p>@p.name - @p.description_product - @p.precio - @p.stock</p>
        @Html.ActionLink("borrar", "deleteProduct", "Inicio", new { id = p.id_product },null)
        @Html.ActionLink("editar", "editProduct", "Inicio", new { id = p.id_product }, null)
    }
}

Views/Inicio/editProduct.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>editProduct</title>
</head>
<body>
    <div> 
        @{
           product pro = ViewBag.product;
        }
        <p>@pro.id_product</p>
        @using (Html.BeginForm("editTheProduct", "Inicio", FormMethod.Post))
        {
            <input name="id" type="text" class="name" value="@pro.id_product"/>
            <input class="name" id="name" name="name" type="text" value="@pro.name"/>
            <input class="description_product" id="description_product" value="@pro.description_product" name="description_product" type="text" />
            <input class="precio" id="precio" name="precio" type="number" value="@pro.precio" />
            <input class="stock" id="stock" name="stock" type="number" value="@pro.stock"/>
            <input type="submit" />
        }
    </div>
</body>
</html>

Views/Shared/myLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>myLayout</title>
    <link type="text/css" rel="stylesheet" href="~/css/styleTemplate.css" />
</head>
<body>
    <div> 
        <header class="header" id="header">
            <div class="logo_menu">
                <div class="div_logo">
                    <a id="">Logo</a>
                </div>
                <div class="div_menu">
                    <a>link 1</a>
                    <a>link 2</a>
                    @Html.ActionLink("salir", "logoutAdmin", "Inicio")
                </div>
            </div>
        </header>
            @RenderBody()
        <footer class="footer">
            &copy Copyright 2020 
        </footer>
    </div>
</body>
</html>